### ISSUE TITLE
Double click doubles the distance before closing

### ISSUE THREAD

**Issue by Hreestos** [gokertanrisever/leaflet-ruler#1]
Hi, I tried your online and offline demo and I noticed that in offline demo when I want to close the path with double click the distance gets doubled before it closes so it reads wrong distance. Also in online demo when I click on the same spot the distance gets doubled.  Attached a photo with two lines one terminated with esc and the other with double click
I think that clicking on the same spot  it should close the path
![map](https://user-images.githubusercontent.com/29738320/27605885-b3472b00-5b86-11e7-9c28-27459573800f.JPG)

**Comment by Hreestos** [comment]
Perhaps removing the doubleclick action in
_toggleMeasure: function()
 and replacing it with 
L.DomEvent.on(this._container, 'click', this._closePath, this);
so as to click the control button to close the path

**Comment by sarlanori** [comment]
I also encountered this problem,and after some attempts,I have solved this problem.
Just modify one line code in:
```
_clicked: function (e) {
    // ...
    if (this._clickCount > 0  && !e.latlng.equals(this._clickedPoints[this._clickedPoints.length - 2])) {
        // ...
     }
    // ...
}
```

**Comment by gokertanrisever** [comment]
Hey, 
@Hreestos thanks for your feedback, @sarlanori's recommendation fixed the issue.
