### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by astomas** [gokertanrisever/leaflet-ruler#11]
can you add an option to display a custom tooltip text when hovering ruler icon ?
Thx

**Comment by dungla2011** [comment]
vote!

**Comment by astomas** [comment]
to do so in lealfet-ruler.js add :
  onAdd: function(map) {  this._map = map;  this._container = L.DomUtil.create('div', 'leaflet-bar');  **this._container.title = 'Measure';** .... }
