### ISSUE TITLE
Double click produces doubling of measurement resulting in incorrect measurement

### ISSUE THREAD

**Issue by WayneTomlinson** [gokertanrisever/leaflet-ruler#15]
Hi

I have been testing your control and its really good. Except I think I have found a bug.
When I double click it sometimes doubles the distance and I cant seem to work out why it does this.

Are you aware of this bug ?

I know it may be a bit of work have your thoight about implementoing a right click to finish the line. This may help differentiate a click that is intended to finish measuring.

If you can fix this issue it would be great.

Thanks

Wayne

**Comment by ZhukDmitry** [comment]
I can tell you. Not double click!
- first click
- move to other place
- second click
- wait
- click again

It is not double click, it is click on the same position
