### ISSUE TITLE
doubleClick error

### ISSUE THREAD

**Issue by StuRuby** [gokertanrisever/leaflet-ruler#2]
when I double click the map, if the two operations are not at the same position, the map will show two markers.Now,I remove the compare between current click and the last click . And in the `_closePath` function,add  a `this._map.removeLayer(this.lastMarker)`;

` _clicked: function(e) {
        this._clickedLatLong = e.latlng;
        this._clickedPoints.push(this._clickedLatLong);
        //L.circleMarker(this._clickedLatLong, this.options.circleMarker).addTo(this._pointLayer);
        //&& !e.latlng.equals(this._clickedPoints[this._clickedPoints.length - 2])
        if(this._clickCount > 0 ){
          if (this._movingLatLong){
            L.polyline([this._clickedPoints[this._clickCount-1], this._movingLatLong], this.options.lineStyle).addTo(this._polylineLayer);
          }
          var text;
          this._totalLength += this._result.Distance;
          if (this._clickCount > 1){
            text =  '距离:' + '</b>&nbsp;' + this._addedLength.toFixed(this.options.lengthUnit.decimal) + '&nbsp;' +  this.options.lengthUnit.display + '<br><div class="plus-length">(+' + this._result.Distance.toFixed(this.options.lengthUnit.decimal) + ')</div>';
          }
          else {
           text = '距离:' + '</b>&nbsp;' + this._result.Distance.toFixed(this.options.lengthUnit.decimal) + '&nbsp;' +  this.options.lengthUnit.display;
         
          }
          this._lastMarker=L.circleMarker(this._clickedLatLong, this.options.circleMarker).bindTooltip(text, {permanent: true, className: 'result-tooltip'}).addTo(this._pointLayer).openTooltip();
        }
        this._clickCount++;
      },`

` _closePath: function() {
        this._map.removeLayer(this._tempLine);
        this._map.removeLayer(this._tempPoint);
        this._map.removeLayer(this._lastMarker);
        this._choice = false;
        L.DomEvent.on(this._container, 'click', this._toggleMeasure, this);
        this._toggleMeasure();
      }`

**Comment by gokertanrisever** [comment]
Hi! Sorry for the late response. 
If I understand correctly, there is a fix here: #9 

Otherwise can you please explain the issue a bit more detailed, or even a pull-request is welcome!
