### ISSUE TITLE
Example quickstart with CDN has outdated hash for leaflet-ruler.js

### ISSUE THREAD

**Issue by treefern** [gokertanrisever/leaflet-ruler#23]
The readme provides the following CDN based quickstart:

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/gokertanrisever/leaflet-ruler@master/src/leaflet-ruler.css" integrity="sha384-P9DABSdtEY/XDbEInD3q+PlL+BjqPCXGcF8EkhtKSfSTr/dS5PBKa9+/PMkW2xsY" crossorigin="anonymous">  
<script src="https://cdn.jsdelivr.net/gh/gokertanrisever/leaflet-ruler@master/src/leaflet-ruler.js" integrity="sha384-N2S8y7hRzXUPiepaSiUvBH1ZZ7Tc/ZfchhbPdvOE5v3aBBCIepq9l+dBJPFdo1ZJ" crossorigin="anonymous"></script>
```

However, the sha384 hash for `leaflet-ruler.js` is incorrect (it appears the readme wasn't updated when the last PR was merged).
The hash should be updated to: `sha384-8SqKZR7V8uOetpjjbcNJHvwuHpb074WS0UXjCLhzfJUqYn3B/uWx1WVv5mwRp1mV`

**Comment by gokertanrisever** [comment]
Thanks for the heads up @treefern! I updated the readme file.  @iliasmachairas do you get any error on the console? This should be working but if you are sure there is an issue feel free to reopen the issue.

**Comment by MahmoudArafaaat** [comment]
Any one can show me how to add this plugin to a folium map in python?
