### ISSUE TITLE
Ruler control on some html element

### ISSUE THREAD

**Issue by UnDetected** [gokertanrisever/leaflet-ruler#5]
For example:

`<div class="some-class">Ruler</div>`

...and on click at this div, I want to activate ruler on the map. On one more click - disactivate.

Now ruler attach to leaflet control. But this is does not suit me and my app design.

**Comment by gokertanrisever** [comment]
Hey @UnDetected, I think this is related to your app design and outside of the scope of this plugin. I think you can still trigger this without needing a change in the plugin. The most simple idea would be something like:
```html
<button onclick="enableRuler()">Start Ruler</button>
```

and in your JS file:

```js
function enableRuler() {
    let ruler = document.getElementsByClassName('leaflet-ruler');
    ruler[0].click();
}
```

I'm closing this issue but please let me know if I didn't understand the case properly.
