### ISSUE TITLE
Control on Custom Button

### ISSUE THREAD

**Issue by MeltedPixel** [gokertanrisever/leaflet-ruler#8]
Hey,

I know this project is no longer maintained. I was wondering if anyone was able to figure out a way to get this to fire off from a non-map oriented button. I have a menu and I want to be able to fire it from that menu.

**Comment by gokertanrisever** [comment]
Hey @MeltedPixel, I apologize for the delayed response. [Here is](https://github.com/gokertanrisever/leaflet-ruler/issues/5#issuecomment-1872187172) my take on this. If it doesn't make sense or if I misunderstood the issue feel free to create a more specific one.
